var SyntaxTree = require("./syntaxTree").SyntaxTree;

/**
 * Builds the syntax tree from the block list generated by the parser.
 * @param {Object} blockList the blockList
 * @return {Object} a JSON structure with the following properties:
 *      syntaxTree: {Object} the syntax tree
 *      errors: {Array} the error list
 */
exports.build = function (blockList) {
    var result = {};
    try {
        var syntaxTree = new SyntaxTree();
        syntaxTree.generateTree(blockList);
        result = {
            syntaxTree : syntaxTree.tree.content,
            errors : syntaxTree.errors
        };
    } catch (ex) {
        result = {
            syntaxTree : null,
            errors : [{
                        description : ex.toString(),
                        line : ex.line,
                        column : ex.column
                    }]
        };
    }
    return result;
};
