var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
var sample = require("hsp/rt").template(["data"], function(n){
  var _changeText;try {_changeText=changeText} catch(e) {_changeText=n.g('changeText')};
  var __s = {changeText : typeof changeText === 'undefined' ? n.g('changeText') : changeText};
  return [__s,n.elt("div",0,{"class":"info2"},0,[n.$text(0,["The following textarea elements are synchronized:"])]),n.elt("div",0,{"class":"section"},0,[n.elt("div",0,0,0,[n.$text(0,["Text #1:"])]),n.elt("textarea",{e1:[1,2,"data","text"]},{"rows":"4","cols":"40","model":["",1]},0)]),n.elt("div",0,{"class":"section"},0,[n.elt("div",0,0,0,[n.$text(0,["Text #2:"])]),n.elt("textarea",{e1:[1,2,"data","text"]},{"rows":"4","cols":"40","model":["",1]},0)]),n.elt("a",{e1:[4,1,_changeText,1,2],e2:[1,1,"data"]},0,{"click":1},[n.$text(0,["Change text"])])];
});


var d={
    // Frog by Donna Shepherd
    text:"    @..@\n   (----)\n  ( >__< )\n ^^ ~~ ^^"
}

var count=1;
function changeText(d) {
    count++, msg=[];
    for (var i=0;count>i;i++) {
        msg.push("This text contains "+count+" lines")
    }
    $set(d, "text", msg.join("\n"));
}

// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
    template: sample,
    data: [d]
});