var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
var message = require("hsp/rt").template(["msg"], function(n){
  var _toggleUrgency,_setCategory,_msg;try {_toggleUrgency=toggleUrgency} catch(e) {_toggleUrgency=n.g('toggleUrgency')};try {_setCategory=setCategory} catch(e) {_setCategory=n.g('setCategory')};try {_msg=msg} catch(e) {_msg=n.g('msg')};
  var __s = {toggleUrgency : typeof toggleUrgency === 'undefined' ? n.g('toggleUrgency') : toggleUrgency, setCategory : typeof setCategory === 'undefined' ? n.g('setCategory') : setCategory, msg : typeof msg === 'undefined' ? n.g('msg') : msg};
  return [__s,n.$text(0,[" "]),n.elt("div",0,0,{"selectstart":"return false"},[n.elt("a",{e1:[9,"toggleUrgency()"]},{"href":"javascript:void(0)"},{"click":1},[n.$text(0,["Change Urgency"])]),n.$text(0,[" - "]),n.elt("a",{e1:[9,"setCategory('personal')"]},{"href":"javascript:void(0)"},{"click":1},[n.$text(0,["Set \"Personal\""])]),n.$text(0,[" - "]),n.elt("a",{e1:[9,"setCategory('professional')"]},{"href":"javascript:void(0)"},{"click":1},[n.$text(0,["Set \"Professional\""])]),n.elt("div",{e1:[9,"msg.category"],e2:[9,"{'urgent':msg.urgency}"]},{"class":["msg ",1," ",2]},0,[n.$text({e1:[9,"msg.text"]},["Message: ",1," "])]),n.elt("div",0,{"class":"note"},0,[n.$text({e1:[9,"msg.category"],e2:[9,"msg.urgency ? 'urgent' : ''"]},["Class value: \"msg ",1," ",2,"\" "])])])];
});


var msg={
    text:"Hello World",
    urgency:false
}

function toggleUrgency() {
    $set(msg, "urgency", !msg.urgency);
}

function setCategory(cat) {
    $set(msg, "category", cat);
}

// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
    template: message,
    data: [msg]
});