
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

require("hsp/rt/log").error("Invalid expression: ''msg', 'urgent':msg.urgency, msg.category'",{"type":"error","file":"inline.js","line":11,"column":27});
