var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
var message = require("hsp/rt").template(["msg"], function(n){
  var _toggleUrgency,_setCategory;try {_toggleUrgency=toggleUrgency} catch(e) {_toggleUrgency=n.g('toggleUrgency')};try {_setCategory=setCategory} catch(e) {_setCategory=n.g('setCategory')};
  return [n.$text(0,[" "]),n.elt("div",0,0,{"selectstart":"return false"},[n.elt("a",{e1:[4,1,_toggleUrgency]},0,{"click":1},[n.$text(0,["Change Urgency"])]),n.$text(0,[" - "]),n.elt("a",{e1:[4,1,_setCategory,0,"personal"]},0,{"click":1},[n.$text(0,["Set \"Personal\""])]),n.$text(0,[" - "]),n.elt("a",{e1:[4,1,_setCategory,0,"professional"]},0,{"click":1},[n.$text(0,["Set \"Professional\""])]),n.elt("div",{e1:[6,function(a0,a1) {return ["msg",((a0)? ''+"urgent":''),a1].join(' ');},2,3],e2:[1,2,"msg","urgency"],e3:[1,2,"msg","category"]},{"class":["",1]},0,[n.$text({e1:[1,2,"msg","text"]},["Message: ",1," "])]),n.elt("div",0,{"class":"note"},0,[n.$text({e1:[6,function(a0,a1) {return ["msg",((a0)? ''+"urgent":''),a1].join(' ');},2,3],e2:[1,2,"msg","urgency"],e3:[1,2,"msg","category"]},["Class value: \"",1,"\" "])])])];
});


var msg={
    text:"Hello World",
    urgency:false
}

function toggleUrgency() {
    $set(msg, "urgency", !msg.urgency);
}

function setCategory(cat) {
    $set(msg, "category", cat);
}

// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
    template: message,
    data: [msg]
});