var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
// edit me!

var hello = require("hsp/rt").template(["name"], function(n){
  return [n.elt("div",0,{"class":"msg"},0,[n.$text({e1:[1,1,"name"]},["Hello ",1,"! "])])];
});


// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
  template: hello,
  data: ["World"]
});