var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
// edit me!

var hello = require("hsp/rt").template(["name"], function(n){
  var _name;try {_name=name} catch(e) {_name=n.g('name')};
  var __s = {name : typeof name === 'undefined' ? n.g('name') : name};
  return [__s,n.elt("div",0,{"class":"msg"},0,[n.$text({e1:[9,"name"]},["Hello ",1,"! "])])];
});


// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
  template: hello,
  data: ["World"]
});