var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

require('hsp/gestures/index').register();


var gestures = require("hsp/rt").template(["msgList"], function(n){
  var _addMsg,_$event,_clearMsg,_msgList,_msg;try {_addMsg=addMsg} catch(e) {_addMsg=n.g('addMsg')};try {_$event=$event} catch(e) {_$event=n.g('$event')};try {_clearMsg=clearMsg} catch(e) {_clearMsg=n.g('clearMsg')};try {_msgList=msgList} catch(e) {_msgList=n.g('msgList')};try {_msg=msg} catch(e) {_msg=n.g('msg')};
  var __s = {addMsg : typeof addMsg === 'undefined' ? n.g('addMsg') : addMsg, $event : typeof $event === 'undefined' ? n.g('$event') : $event, clearMsg : typeof clearMsg === 'undefined' ? n.g('clearMsg') : clearMsg, msgList : typeof msgList === 'undefined' ? n.g('msgList') : msgList, msg : typeof msg === 'undefined' ? n.g('msg') : msg};
  return [__s,n.elt("div",{e1:[9,"addMsg($event)"],e2:[9,"addMsg($event)"],e3:[9,"addMsg($event)"],e4:[9,"addMsg($event)"],e5:[9,"addMsg($event)"],e6:[9,"addMsg($event)"],e7:[9,"addMsg($event)"],e8:[9,"addMsg($event)"],e9:[9,"addMsg($event)"],e10:[9,"addMsg($event)"],e11:[9,"addMsg($event)"],e12:[9,"addMsg($event)"],e13:[9,"addMsg($event)"],e14:[9,"addMsg($event)"],e15:[9,"addMsg($event)"],e16:[9,"addMsg($event)"],e17:[9,"addMsg($event)"],e18:[9,"addMsg($event)"],e19:[9,"addMsg($event)"],e20:[9,"addMsg($event)"],e21:[9,"addMsg($event)"],e22:[9,"addMsg($event)"],e23:[9,"addMsg($event)"],e24:[9,"addMsg($event)"]},{"class":"touchboard","style":"height:200px; background: #27AAFC;text-align:center;"},{"tap":1,"tapstart":2,"tapcancel":3,"longpress":4,"longpressstart":5,"longpresscancel":6,"singletap":7,"singletapstart":8,"singletapcancel":9,"doubletap":10,"doubletapstart":11,"doubletapcancel":12,"swipe":13,"swipestart":14,"swipemove":15,"swipecancel":16,"drag":17,"dragstart":18,"dragmove":19,"dragcancel":20,"pinch":21,"pinchstart":22,"pinchmove":23,"pinchcancel":24},[n.elt("h1",0,0,0,[n.$text(0,["TOUCH ME"])])]),n.elt("div",0,{"class":"msglist","style":"min-height: 50px;"},0,[n.elt("div",{e1:[9,"clearMsg()"]},{"style":"float:right; background: #27AAFC; padding:10px; margin-top:10px;"},{"tap":1},[n.$text(0,["Clear logs"])]),n.$foreach({e1:[9,"msgList"]},"msg_key","msg",0,1,[n.elt("div",0,0,0,[n.$text({e1:[9,"msg"]},["",1])])]),n.$text(0,[" "])])];
});


var eventLog = [];

function addMsg(evt) {
	eventLog.push(evt.duration + "ms - " + evt.type + " from " + evt.target.tagName);
}

function clearMsg() {
    eventLog.splice(0,eventLog.length);

}

// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
    template: gestures,
    data: [eventLog]
});