var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
var list = require("hsp/rt").template(["persons"], function(n){
  var _persons,_orderBy,_p,_Sorter,_nameSorter;try {_persons=persons} catch(e) {_persons=n.g('persons')};try {_orderBy=orderBy} catch(e) {_orderBy=n.g('orderBy')};try {_p=p} catch(e) {_p=n.g('p')};try {_Sorter=Sorter} catch(e) {_Sorter=n.g('Sorter')};try {_nameSorter=nameSorter} catch(e) {_nameSorter=n.g('nameSorter')};
  var __s = {persons : typeof persons === 'undefined' ? n.g('persons') : persons, orderBy : typeof orderBy === 'undefined' ? n.g('orderBy') : orderBy, p : typeof p === 'undefined' ? n.g('p') : p, Sorter : typeof Sorter === 'undefined' ? n.g('Sorter') : Sorter, nameSorter : typeof nameSorter === 'undefined' ? n.g('nameSorter') : nameSorter};
  return [__s,n.elt("div",0,0,{"selectstart":"return false"},[n.elt("div",0,{"class":"msg"},0,[n.elt("span",0,{"class":"info"},0,[n.$text(0,["List sorted with the orderBy() function: "])]),n.elt("ol",0,0,0,[n.$foreach({e1:[9,"persons|orderBy:\"name\""]},"p_key","p",0,1,[n.elt("li",0,0,0,[n.$text({e1:[9,"p.name"]},["",1])])]),n.$text(0,[" "])])]),n.elt("hr",0,0,0),n.elt("div",0,{"class":"msg"},0,[n.let({e1:[9,"nameSorter=new Sorter({property:\"name\",states:\"ADN\"})"]}),n.elt("span",0,{"class":"info"},0,[n.$text({e1:[9,"nameSorter.state"]},["List sorted with a Sorter object (current state: ",1,") "])]),n.elt("ol",0,0,0,[n.$foreach({e1:[9,"persons|nameSorter"]},"p_key","p",0,1,[n.elt("li",0,0,0,[n.$text({e1:[9,"p.name"]},["",1])])]),n.$text(0,[" "])]),n.elt("a",{e1:[3,2,"nameSorter","nextState"]},0,{"click":1},[n.$text(0,["Change sort order"])])],1)])];
});


var people = [
    {name:"Homer", age:38},
    {name:"Marge", age:38},
    {name:"Bart", age:10},
    {name:"Lisa", age:8},
    {name:"Maggie", age:1}
];

// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
    template: list,
    data: [people]
});