var $set=require("hsp/$set"); 
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 
var list = require("hsp/rt").template(["persons"], function(n){
  var _orderBy,_Sorter;try {_orderBy=orderBy} catch(e) {_orderBy=n.g('orderBy')};try {_Sorter=Sorter} catch(e) {_Sorter=n.g('Sorter')};
  var __s = {orderBy : typeof orderBy === 'undefined' ? undefined : orderBy, Sorter : typeof Sorter === 'undefined' ? undefined : Sorter};
  return [__s,n.elt("div",0,0,{"selectstart":"return false"},[n.elt("div",0,{"class":"msg"},0,[n.elt("span",0,{"class":"info"},0,[n.$text(0,["List sorted with the orderBy() function: "])]),n.elt("ol",0,0,0,[n.$foreach({e1:[4,1,_orderBy,1,2,0,"name"],e2:[1,1,"persons"]},"p_key","p",0,1,[n.elt("li",0,0,0,[n.$text({e1:[1,2,"p","name"]},["",1])])]),n.$text(0,[" "])])]),n.elt("hr",0,0,0),n.elt("div",0,{"class":"msg"},0,[n.let({e1:[6,function(a0) {return new a0({property:"name",states:"ADN"});},2],e2:[2,1,_Sorter]},['nameSorter',1]),n.elt("span",0,{"class":"info"},0,[n.$text({e1:[1,2,"nameSorter","state"]},["List sorted with a Sorter object (current state: ",1,") "])]),n.elt("ol",0,0,0,[n.$foreach({e1:[3,1,"nameSorter",1,2],e2:[1,1,"persons"]},"p_key","p",0,1,[n.elt("li",0,0,0,[n.$text({e1:[1,2,"p","name"]},["",1])])]),n.$text(0,[" "])]),n.elt("a",{e1:[3,2,"nameSorter","nextState"]},0,{"click":1},[n.$text(0,["Change sort order"])])],1)])];
});


var people = [
    {name:"Homer", age:38},
    {name:"Marge", age:38},
    {name:"Bart", age:10},
    {name:"Lisa", age:8},
    {name:"Maggie", age:1}
];

// Needed by the playground application.
// Update it, but do not remove it!
$set(module, "exports", {
    template: list,
    data: [people]
});