
// ################################################################ 
//  This file has been generated by the hashspace compiler          
//  Direct MODIFICATIONS WILL BE LOST when the file is recompiled!  
// ################################################################ 

require("hsp/rt/log").error("SyntaxError: The keyword 'export' is reserved",{"type":"error","file":"inline.js","code":"{export template personList(persons)}","line":2,"column":1});
